#ifndef GRID_QCD_STAGGAMMA_H
#define GRID_QCD_STAGGAMMA_H

// code generated by the Mathematica notebook gamma-gen/gamma-gen.nb

#include <array>
#include <Grid/qcd/spin/Gamma.h>

NAMESPACE_BEGIN(Grid)

class StagGamma {
  public:
    Gamma::Algebra                                                      g_spin,g_taste;
  public:
    StagGamma(Gamma::Algebra initg_spin,Gamma::Algebra initg_taste): g_spin(initg_spin),g_taste(initg_taste) {}
    StagGamma(std::pair<Gamma::Algebra,Gamma::Algebra> initg): g_spin(initg.first),g_taste(initg.second) {}
};

// Dirac algebra adjoint operator (not in  to overload other adj)
inline StagGamma adj(const StagGamma &g)
{
  return StagGamma(Gamma::adj[g.g_spin],Gamma::adj[g.g_taste]);
}

inline bool operator<(const StagGamma &g1, const StagGamma &g2) {
  if (Gamma::nGamma*(g1.g_spin-g2.g_spin)+(g1.g_taste-g2.g_taste) < 0)
    return true;
  else
    return false;
}


// Dirac algebra mutliplication operator
inline StagGamma operator*(const StagGamma &g1, const StagGamma &g2)
{
  return StagGamma(Gamma::mul[g1.g_spin][g2.g_spin],Gamma::mul[g1.g_taste][g2.g_taste]);
}

template<class obj> inline
Lattice<obj> operator*(const StagGamma &G, const Lattice<obj> &rhs){
  return rhs*G;
}

template<class obj> inline
Lattice<obj> operator*(const Lattice<obj> &lhs, const StagGamma &G){

  GridBase * grid = lhs.Grid();
  Lattice<iScalar<vInteger> > x(grid); LatticeCoordinate(x,0);
  Lattice<iScalar<vInteger> > y(grid); LatticeCoordinate(y,1);
  Lattice<iScalar<vInteger> > z(grid); LatticeCoordinate(z,2);
  Lattice<iScalar<vInteger> > t(grid); LatticeCoordinate(t,3);
  Lattice<iScalar<vInteger> > lin_x(grid); lin_x=y+z+t;
  Lattice<iScalar<vInteger> > lin_y(grid); lin_y=x+z+t;
  Lattice<iScalar<vInteger> > lin_z(grid); lin_z=x+y+t;
  Lattice<iScalar<vInteger> > lin_5(grid); lin_5=x+y+z+t;

  LatticeComplex stag_phase(grid);

  stag_phase = 1.0;

  if (G.g_spin == G.g_taste) {
    switch(G.g_spin) {
    case Gamma::Algebra::Identity:
      break;
    case Gamma::Algebra::GammaX:
      stag_phase = where(mod(lin_x,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::GammaY:
      stag_phase = where(mod(lin_y,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::GammaZ:
      stag_phase = where(mod(lin_z,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::Gamma5:
      stag_phase = where(mod(lin_5,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::GammaXGamma5:
      stag_phase = where(mod(x,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::GammaYGamma5:
      stag_phase = where(mod(y,2)==0,stag_phase,-stag_phase);
      break;
    case Gamma::Algebra::GammaZGamma5:
      stag_phase = where(mod(z,2)==0,stag_phase,-stag_phase);
      break;
    default:
      assert(0);
    }
  } else {
    assert(0);
  }

  return lhs*stag_phase;
}

NAMESPACE_END(Grid)

#endif // GRID_QCD_STAGGAMMA_H
